package db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import business.Actor;
import business.Movie;

public class ActorDB implements DAOUploadable<Actor> {
	private Connection getConnection() throws SQLException {
		String dbURL = "jdbc:mysql://localhost:3306/bmdb";
		String userName = "bmdb_user";
		String password = "sesame";
		Connection conn = DriverManager.getConnection(dbURL, userName, password);
		return conn;
	}
	
	
	@Override
	public Actor getById(int id) {
		Actor a = null;
		String sql = "select * from actor where id = ?";
		
		try (Connection conn = getConnection();
				PreparedStatement ps = conn.prepareStatement(sql);){
			ps.setInt(1, id);			
			ResultSet rs = ps.executeQuery();
			if (rs.next()) {
				a = getActorFromResultSet(rs);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			System.out.println("Error with finding actor by id.");
			e.printStackTrace();
		}
		return a;
	}

	@Override
	public List<Actor> getAll() {
		List<Actor> actors = new ArrayList<>();
		String sql = "select * from actor;";
		try (Connection conn = getConnection();
				 Statement stmt = conn.createStatement();
				 ResultSet rs = stmt.executeQuery(sql)) {
				// p 681 - processing result set
				while (rs.next()) {
					Actor a = getActorFromResultSet(rs);
					actors.add(a);
				}
			} catch (SQLException e) {
				System.err.println("Error getting all actors.");
				e.printStackTrace();
			}
			
			return actors;
		}

	private Actor getActorFromResultSet(ResultSet rs) throws SQLException {
		int id = rs.getInt(1);
		String firstName = rs.getString(2);
		String lastName = rs.getString(3);
		String gender = rs.getString(4);
		String strBirthDate = rs.getString(5);
		LocalDate birthDate = LocalDate.parse(strBirthDate);
		Actor a = new Actor(id, firstName, lastName, gender, birthDate);
		return a;
		}


	@Override
	public boolean add(Actor a) {
		boolean success = false;
		//never declare the id when adding - it is autogenerated
		String sql = "insert into actor (firstName, lastName, gender, birthDate) "
				+ "values(?, ?, ?, ?)";
		try (Connection conn = getConnection();
			 PreparedStatement ps = conn.prepareStatement(sql)) {
			ps.setString(1, a.getFirstName());
			ps.setString(2, a.getLastName());
			ps.setString(3, a.getGender());
			ps.setString(4, a.getBirthDate().toString());
			ps.executeUpdate();
			success = true;
		} catch (SQLException e) {
			System.out.println("Error adding actor.");
			e.printStackTrace();
		}
		return success;
		}

	@Override
	public boolean update(Actor a) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean delete(Actor a) {
		boolean success = false;
		//p 691
		String sql = "delete from actor where id = ?";
		try (Connection conn = getConnection();
			 PreparedStatement ps = conn.prepareStatement(sql)) {
				ps.setInt(1, a.getId());
				ps.executeUpdate();
				success = true;
			} catch (SQLException e) {
				System.out.println("Error deleting actor.");
				e.printStackTrace();
			}
		
		return success;
	}

	@Override
	public boolean upload() {
		// TODO Auto-generated method stub
		return false;
	}

	

}
